import logging
from collections import Counter
from pathlib import Path
from typing import Any

import yaml

from ocrpolish.models.metadata import AggregatedTaggingResult, TopicResult, WindowTaggingResult
from ocrpolish.services.flattening_service import FlatteningService
from ocrpolish.services.ollama_client import OllamaClient
from ocrpolish.services.windowing_service import SlidingWindowService
from ocrpolish.utils.nlp import (
    estimate_tokens,
    filter_low_value_tags,
    normalize_tag_component,
    suppress_duplicates,
)

logger = logging.getLogger(__name__)


class TaggingService:
    """
    Service for extracting tiered tags (Entities, Topics, Conceptual)
    using a dynamic single-pass or sliding-window strategy.
    """

    def __init__(
        self,
        ollama_client: OllamaClient,
        windowing_service: SlidingWindowService,
        themes_path: Path,
        useful_tags_path: Path | None = None,
        context_limit: int = 32000,
        model_name: str = "gemma4:31b",
        flat_mode: bool = False,
    ):
        self.client = ollama_client
        self.windowing_service = windowing_service
        self.themes_path = themes_path
        self.useful_tags_path = useful_tags_path
        self.context_limit = context_limit
        self.model_name = model_name
        self.flat_mode = flat_mode
        self.flattening_service = FlatteningService()

        # Load and Normalize Themes
        raw_themes = self._load_yaml(themes_path)
        self.themes = self._normalize_data(raw_themes)

        # Load and Normalize Useful Tags
        self.useful_tags = []
        if useful_tags_path:
            raw_tags = self._load_yaml(useful_tags_path).get("useful_tags", [])
            self.useful_tags = [normalize_tag_component(t) for t in raw_tags]

    def _normalize_data(self, data: Any) -> Any:
        """Recursively normalize categories and topics in the hierarchy."""
        if isinstance(data, list):
            return [self._normalize_data(item) for item in data]
        if isinstance(data, dict):
            new_dict = {}
            for k, v in data.items():
                if k in ("category", "topic"):
                    new_dict[k] = normalize_tag_component(v)
                else:
                    new_dict[k] = self._normalize_data(v)
            return new_dict
        return data

    def _load_yaml(self, path: Path) -> dict[str, Any]:
        try:
            with open(path, encoding="utf-8") as f:
                data = yaml.safe_load(f)
                return data if isinstance(data, dict) else {}
        except Exception as e:
            logger.error(f"Failed to load YAML from {path}: {e}")
            return {}

    def extract_tags(self, text: str) -> AggregatedTaggingResult:
        """
        Performs the second-pass tagging using a dynamic strategy.
        """
        tokens = estimate_tokens(text)

        if tokens <= self.context_limit:
            logger.debug(f"Using single pass for tagging ({tokens} tokens)")
            window_result = self._extract_chunk(text)
            
            # Normalize entities
            normalized_entities = []
            for entity in window_result.entity_tags:
                parts = entity.split("/")
                norm_parts = [normalize_tag_component(p) for p in parts]
                normalized_entities.append("/".join(norm_parts))
            entities_list = sorted(list(set(normalized_entities)))
            
            # Normalize topics and keep reasons
            topics_dict: dict[str, TopicResult] = {}
            for tr in window_result.topic_tags:
                parts = tr.topic.split("/")
                norm_parts = [normalize_tag_component(p) for p in parts]
                norm_topic = "/".join(norm_parts)
                if norm_topic not in topics_dict:
                    tr.topic = norm_topic
                    topics_dict[norm_topic] = tr
            
            topics_list = sorted(topics_dict.values(), key=lambda x: x.topic)
            topic_names = [t.topic for t in topics_list]
            
            # Normalize conceptual tags (take all generated by LLM)
            normalized_conceptual = [normalize_tag_component(t) for t in window_result.conceptual_tags]
            
            # Apply filtering and suppression
            filtered_conceptual = filter_low_value_tags(normalized_conceptual)
            suppressed_conceptual = suppress_duplicates(filtered_conceptual, entities_list, topic_names)
            
            return AggregatedTaggingResult(
                conceptual_tags=suppressed_conceptual,
                entity_tags=entities_list,
                topic_tags=topics_list,
            )

        logger.debug(f"Using sliding window for tagging ({tokens} tokens)")
        chunks = self.windowing_service.get_windows(text)

        # Aggregate and Normalize
        conceptual_counter: Counter[str] = Counter()
        all_entities = set()
        topics_dict = {}

        for chunk in chunks:
            window_result = self._extract_chunk(chunk)
            
            # Normalize and update
            for t in window_result.conceptual_tags:
                conceptual_counter.update([normalize_tag_component(t)])
            
            for e in window_result.entity_tags:
                parts = e.split("/")
                norm_parts = [normalize_tag_component(p) for p in parts]
                all_entities.add("/".join(norm_parts))
                
            for tr in window_result.topic_tags:
                parts = tr.topic.split("/")
                norm_parts = [normalize_tag_component(p) for p in parts]
                norm_topic = "/".join(norm_parts)
                if norm_topic not in topics_dict:
                    tr.topic = norm_topic
                    topics_dict[norm_topic] = tr

        # Take top 100 conceptual tags by frequency to ensure robust context
        top_conceptual = [tag for tag, _ in conceptual_counter.most_common(100)]

        # Apply global filtering and suppression
        filtered_conceptual = filter_low_value_tags(top_conceptual)
        entities_list = sorted(list(all_entities))
        topics_list = sorted(topics_dict.values(), key=lambda x: x.topic)
        topic_names = [t.topic for t in topics_list]
        suppressed_conceptual = suppress_duplicates(filtered_conceptual, entities_list, topic_names)

        return AggregatedTaggingResult(
            conceptual_tags=suppressed_conceptual,
            entity_tags=entities_list,
            topic_tags=topics_list,
        )

    def _extract_chunk(self, chunk: str) -> WindowTaggingResult:
        """
        Extracts tags from a single chunk of text using a non-thinking model.
        """
        prompt = self._generate_tagging_prompt(chunk)
        try:
            return self.client.extract_structured(
                prompt, WindowTaggingResult, model=self.model_name, think=False
            )
        except Exception as e:
            logger.error(f"Error extracting tags from chunk: {e}")
            return WindowTaggingResult()

    def _generate_tagging_prompt(self, text: str) -> str:
        """
        Generates the prompt for the tagging pass.
        """
        if self.flat_mode:
            taxonomy = self.flattening_service.flatten(self.themes)
            topic_format = "Category/Topic"
            topic_instruction = "Select the most important topics from the flat taxonomy below."
        else:
            taxonomy = self.themes
            topic_format = "Category/<category>/<topic>"
            topic_instruction = "Hierarchical tags from the approved taxonomy below."
            
        taxonomy_info = yaml.dump(taxonomy, sort_keys=False)
        useful_tags_str = ", ".join(self.useful_tags)

        return (
            "Document Excerpt:\n\n"
            f"{text}\n\n"
            "Based on the content above, extract precision tags in three categories:\n\n"
            "1. 'entity_tags': Hierarchical tags for mentioned entities. "
            "Use formats: State/<name>, Org/<name>, City/<state>/<city>, Person/<name>.\n"
            f"2. 'topic_tags': {topic_instruction} "
            f"Use format: {topic_format}. Include a brief 'reason' for each.\n"
            "3. 'conceptual_tags': Up to 15 flat, canonical tags for archivally substantive concepts. "
            "PRIORITIZE re-using tags from the vocabulary below. Normalize exercises as Name/YY. "
            "MANDATORY: Include all all-caps abbreviations mentioned in the text (e.g., SACEUR, SACLANT, CINCHAN).\n\n"
            "APPROVED TAXONOMY (YAML):\n"
            f"{taxonomy_info}\n\n"
            "EXISTING VOCABULARY (USEFUL TAGS):\n"
            f"{useful_tags_str}\n\n"
            "CRITICAL RULES:\n"
            "- Only include tags that are clearly justified by the text.\n"
            "- Exclude routine administrative labels (agenda, report, notice, corrigendum).\n"
            "- Ensure hierarchical formats are strictly followed.\n"
            "- Conceptual tags MUST NOT duplicate entities or topics."
        )
